// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/31/2025, 12:48:27 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/scrubbed2520/Desktop/apps/spendwise/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/plugins/**/*.{js,ts,mjs}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/composables/**/*.{js,ts,mjs}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/utils/**/*.{js,ts,mjs}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/spendwise/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;