// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/28/2025, 8:04:36 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/scrubbed2520/Desktop/apps/expensewise/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/plugins/**/*.{js,ts,mjs}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/composables/**/*.{js,ts,mjs}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/utils/**/*.{js,ts,mjs}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/scrubbed2520/Desktop/apps/expensewise/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;